### ISSUE TITLE
[🐞]: Incompatibility with DramaticDoors mod

### ISSUE THREAD

**Issue by akai-hana** [MehVahdJukaar/WoodGood#332]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Fabric

### EveryCompat Version

everycomp-1.19.2-2.5.14-fabric

### Moonlight Lib Version

moonlight-1.19.2-2.3.5-fabric

### Issue with mods

DramaticDoors-Fabric-1.19.2-2.0.1

### Issue Detail

Install both mods together, Minecraft will crash. They work separately tho.

Here's some interesting code lines from the logs.

`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'everycomp'!`

`Caused by: java.lang.NoClassDefFoundError: com/fizzware/dramaticdoors/fabric/blocks/ShortDoorBlock`

This is most likely the cause of the crash.

If I'm missing any key info, please LMK and I'll provide it.

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2023-11-09_12.04.17-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/13307279/crash-2023-11-09_12.04.17-client.txt)

### OPTIONAL: To Produce

1) Install dramaticoors and everycomp 1.19.2 fabric, lastest version
2) crash

**Comment by akai-hana** [comment]
im an idiot. nevermind.

**Comment by OrganicHoney** [comment]
How did you fix this? I'm having the same issue.
